export const NAVIGATION = {
  login: 'Login',
  loginStack: 'LoginStack',
  home: 'Home',
  UserList: 'UserList',
  UserAdd: 'UserAdd',
  SiteList: 'SiteList',
  SiteAdd: 'SiteAdd',
  VenderList: 'VenderList',
  VenderAdd: 'VenderAdd',
  ExpensesList: 'ExpensesList',
  ExpensesAdd: 'ExpensesAdd',
  ExpensesTypeList: 'ExpensesTypeList',
  ExpensesTypeAdd: 'ExpensesTypeAdd',
  Report: 'Report',
  ReportPDF: 'ReportPDF',
  SignUp: 'SignUp',
};
